### PR TITLE
margin fixed for small and normal flags

### LINKED ISSUE #92: get rid of hidden margin?
Right now the sprites seem to have some sort of hidden margin, possibly described in issue #14 

I would like the flag sprite to have no margin at all, and to be exactly as big as the sprite itself, so that I can avoid issues like this:

image

Where there is a huge hidden margin (padding?) that won't allow the flag to align with the flexbox's `aligh-items: flex-end` prop:

image

The height of the `<span>` that the package renders is fine I think

image

But the browser tools show a different height/width without margin or padding:

image

For reference, here's the element in the console:

image

### PR DESCRIPTION
**Pull request by P3trur0**
This fixes #92.

Since normal and small flags are a scaling of the big one, a margin is automatically added. To fix this, some margin needs to be removed from them.

### CODE REVIEW

File: packages/vue-country-flag/src/CountryFlag.vue [hunk 1]
```diff
@@ -65,12 +65,14 @@ export default {
...
 <style scoped>
   .small-flag {
+    margin: -0.9em -1.2em -0.9em -1.2em;
     transform: scale(0.25);
     -ms-transform: scale(0.25); 
     -webkit-transform: scale(0.25);
     -moz-transform: scale(0.25);
   }
   .normal-flag {
+    margin: 0em -0.9em -0.6em -0.7em;
```
Comment (bicouy0) [inline packages/vue-country-flag/src/CountryFlag.vue:75]: I think it should be 
```css
margin: -10px -13px;
```
because your original image is 52x39, scale by 0.5 : 26x19.5, divided by 2 : 13x9.75

File: packages/vue-country-flag/src/CountryFlag.vue [hunk 2]
```diff
@@ -65,12 +65,14 @@ export default {
 </script>
 <style scoped>
   .small-flag {
+    margin: -0.9em -1.2em -0.9em -1.2em;
```
Comment (bicouy0) [inline packages/vue-country-flag/src/CountryFlag.vue:68]: Should be
```css
margin: -15px -20px;
```

original is 52x39, remainder of 0.25 scale : 39x29.25, divided by 2 : 19.5x14.6
